// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZggddo01mSxxlw9_IoNmCA25kxeFZsQU',
    appId: '1:372872315566:web:b7b59e01160093374f233f',
    messagingSenderId: '372872315566',
    projectId: 'medura-d7973',
    authDomain: 'medura-d7973.firebaseapp.com',
    storageBucket: 'medura-d7973.firebasestorage.app',
    measurementId: 'G-00Q6Z15CM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA7nqdqV__occ0-qgOYEGSYnZcmzPG8qw',
    appId: '1:372872315566:android:99f171cc6f1ed4f04f233f',
    messagingSenderId: '372872315566',
    projectId: 'medura-d7973',
    storageBucket: 'medura-d7973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjVE3VVcUiHBzMCkQyLmTHRFHXCVKcLk',
    appId: '1:372872315566:ios:7f3a268fb681e3944f233f',
    messagingSenderId: '372872315566',
    projectId: 'medura-d7973',
    storageBucket: 'medura-d7973.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthcareAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjVE3VVcUiHBzMCkQyLmTHRFHXCVKcLk',
    appId: '1:372872315566:ios:7f3a268fb681e3944f233f',
    messagingSenderId: '372872315566',
    projectId: 'medura-d7973',
    storageBucket: 'medura-d7973.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthcareAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZggddo01mSxxlw9_IoNmCA25kxeFZsQU',
    appId: '1:372872315566:web:f87e0a3d4f396fd24f233f',
    messagingSenderId: '372872315566',
    projectId: 'medura-d7973',
    authDomain: 'medura-d7973.firebaseapp.com',
    storageBucket: 'medura-d7973.firebasestorage.app',
    measurementId: 'G-0MV8WNFX4J',
  );
}
